name: Build LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true

      - name: Move PDF to Public Directory
        run: |
          mkdir -p public
          mv resume.pdf public/

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages   # This ensures GitHub Pages receives the correct artifact name
          path: public

  deploy:
    needs: build_latex
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
